Issue {issueClosedAt = Nothing, issueUpdatedAt = GithubDate {fromGithubDate = 2013-02-04 05:50:21 UTC}, issueHtmlUrl = "https://github.com/pydata/patsy/issues/14", issueClosedBy = Nothing, issueLabels = [], issueNumber = 14, issueAssignee = Nothing, issueUser = GithubUser {githubOwnerAvatarUrl = "https://secure.gravatar.com/avatar/4778273746a92044a5bd6b4a751749ae?d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-user-420.png", githubOwnerLogin = "setjmp", githubOwnerUrl = "https://api.github.com/users/setjmp", githubOwnerId = 30059, githubOwnerGravatarId = "4778273746a92044a5bd6b4a751749ae"}, issueTitle = "Patsy prints uninformative error message when user places \"Intercept\" in a formula", issuePullRequest = PullRequestReference {pullRequestReferenceHtmlUrl = Nothing, pullRequestReferencePatchUrl = Nothing, pullRequestReferenceDiffUrl = Nothing}, issueUrl = "https://api.github.com/repos/pydata/patsy/issues/14", issueCreatedAt = GithubDate {fromGithubDate = 2013-02-04 04:44:59 UTC}, issueBody = "This is observed on patsy 0.1.0.\r\n\r\nI saw that the design_info object of a design matrix uses \"Intercept\" as the encoding for the intercept term so I wondered what would happen if a programmer chose this as the name for a feature.\r\n\r\nThe ideal scenerio is that patsy either:\r\n  a.  Does some name mangling\r\n  b.  throws an error telling me exactly what I did wrong if this is not going to be supported\r\n\r\nWhat happens in reality is that an uniformative assertion message is produced:\r\n\r\n```Traceback (most recent call last):\r\n  File \"failure.py\", line 5, in <module>\r\n    y,X = patsy.dmatrices(\"sl ~ Intercept\",dataFrame)\r\n  File \"build/bdist.macosx-10.8-intel/egg/patsy/highlevel.py\", line 283, in dmatrices\r\n  File \"build/bdist.macosx-10.8-intel/egg/patsy/highlevel.py\", line 150, in _do_highlevel_design\r\n  File \"build/bdist.macosx-10.8-intel/egg/patsy/build.py\", line 860, in build_design_matrices\r\n  File \"build/bdist.macosx-10.8-intel/egg/patsy/build.py\", line 776, in _build\r\n  File \"build/bdist.macosx-10.8-intel/egg/patsy/build.py\", line 757, in design_info\r\n  File \"build/bdist.macosx-10.8-intel/egg/patsy/design_info.py\", line 78, in __init__\r\nAssertionError```\r\n\r\nHere is the code that produces the error:\r\n```\r\nimport pandas\r\nimport patsy\r\n\r\ndataFrame = pandas.io.parsers.read_csv(\"salary2.txt\") \r\ny,X = patsy.dmatrices(\"sl ~ Intercept\",dataFrame) \r\n```", issueState = "open", issueId = 10595680, issueComments = 1, issueMilestone = Nothing}